[Main]
RealAppId=2622380
FakeAppId=480

#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false


[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false


[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true


[DLC]
3637850=ELDEN RING NIGHTREIGN CE Content (Retail)
3515610=ELDEN RING NIGHTREIGN - Deluxe Upgrade Pack
3515600=ELDEN RING NIGHTREIGN Digital Artbook & Mini Soundtrack
3319490=ELDEN RING NIGHTREIGN Bonus Gesture


[Hashes]
0=c2e33f5c2c54b0e9131f21c1dce3b953f931049424b0b694f1b469f6cd1698cf2ddf208fb6bcd76a7c4d16a3488dc0f6d2854b0af265d0745f1aee3536095dcc
1337=f78d62734c4cb0e680bc8fb015163a2ac6e73aa9b2a9f627b8f4bd5d0814f053942f1e556d06b0fde73d7e692900d7edfa5f971754b3f8b484626d7bbf48a46c
